DROP POLICY IF EXISTS sport_time_defaults_read_all       ON sport_time_defaults;
DROP POLICY IF EXISTS rally_rach_points_read_all         ON rally_rach_points;
DROP POLICY IF EXISTS om_points_read_all                 ON om_points;
DROP POLICY IF EXISTS otch_points_read_all               ON otch_points;
DROP POLICY IF EXISTS obedience_class_exercises_read_all ON obedience_class_exercises;
DROP POLICY IF EXISTS obedience_exercises_read_all       ON obedience_exercises;
DROP POLICY IF EXISTS jump_heights_read_all              ON jump_heights;
DROP POLICY IF EXISTS title_suffixes_read_all            ON title_suffixes;
DROP POLICY IF EXISTS title_prefixes_read_all            ON title_prefixes;
DROP POLICY IF EXISTS breed_varieties_read_all           ON breed_varieties;
DROP POLICY IF EXISTS breeds_read_all                    ON breeds;
DROP POLICY IF EXISTS breed_groups_read_all              ON breed_groups;
DROP POLICY IF EXISTS states_read_all                    ON states;
DROP POLICY IF EXISTS countries_read_all                 ON countries;

ALTER TABLE sport_time_defaults       DISABLE ROW LEVEL SECURITY;
ALTER TABLE rally_rach_points         DISABLE ROW LEVEL SECURITY;
ALTER TABLE om_points                 DISABLE ROW LEVEL SECURITY;
ALTER TABLE otch_points               DISABLE ROW LEVEL SECURITY;
ALTER TABLE obedience_class_exercises DISABLE ROW LEVEL SECURITY;
ALTER TABLE obedience_exercises       DISABLE ROW LEVEL SECURITY;
ALTER TABLE jump_heights              DISABLE ROW LEVEL SECURITY;
ALTER TABLE title_suffixes            DISABLE ROW LEVEL SECURITY;
ALTER TABLE title_prefixes            DISABLE ROW LEVEL SECURITY;
ALTER TABLE breed_varieties           DISABLE ROW LEVEL SECURITY;
ALTER TABLE breeds                    DISABLE ROW LEVEL SECURITY;
ALTER TABLE breed_groups              DISABLE ROW LEVEL SECURITY;
ALTER TABLE states                    DISABLE ROW LEVEL SECURITY;
ALTER TABLE countries                 DISABLE ROW LEVEL SECURITY;

REVOKE ALL ON sport_time_defaults        FROM qtrial_tenant;
REVOKE ALL ON rally_rach_points          FROM qtrial_tenant;
REVOKE ALL ON om_points                  FROM qtrial_tenant;
REVOKE ALL ON otch_points                FROM qtrial_tenant;
REVOKE ALL ON obedience_class_exercises  FROM qtrial_tenant;
REVOKE ALL ON obedience_exercises        FROM qtrial_tenant;
REVOKE ALL ON jump_heights               FROM qtrial_tenant;
REVOKE ALL ON title_suffixes             FROM qtrial_tenant;
REVOKE ALL ON title_prefixes             FROM qtrial_tenant;
REVOKE ALL ON breed_varieties            FROM qtrial_tenant;
REVOKE ALL ON breeds                     FROM qtrial_tenant;
REVOKE ALL ON breed_groups               FROM qtrial_tenant;
REVOKE ALL ON states                     FROM qtrial_tenant;
REVOKE ALL ON countries                  FROM qtrial_tenant;
